### ISSUE TITLE
The game crashes 

### ISSUE THREAD

**Issue by Tsuraj56** [McMellonTeam/pistonpushmod#2]
the game crashes when mod is install in 1.20.1 ,  i use this cammand /gamerule PistonPushingLimit 14

**Comment by RodoFire** [comment]
hello, can you send me your crash report? It is located on the crash report folder under the .minecraft folder of your instance folder if you use a custom launcher. Also, what is your mod version?

**Comment by RodoFire** [comment]
and also, do you use any other mod?

**Comment by RodoFire** [comment]
if you want me to solve this issue, you should send me more details

**Comment by Tsuraj56** [comment]
Sorry for late reply.I am Currently not using this mod now I am using carpet mod. But if u want I can help u tho

**Comment by RodoFire** [comment]
No problem, but it could be great to understand the problem so that the other people that wanna use this mod wouldn't face this issue. As mentionned earlier, can you send me your crash report? It is located on the crash report folder under the .minecraft folder or your instance folder if you use a custom launcher. Also, what is your mod version?

**Comment by Tsuraj56** [comment]
The game is not crashing now  i am pushpiston 1,1,1 version but now pistons are not moving . i mean their are not extending. And sorry again for late reply i am very busy as i am learning modding and other thing too

**Comment by RodoFire** [comment]
that might be an issue with the carpet mod since that it modify a lot of piston behavior while I only add the possibility to increase/ decrease the push limit. Can you send me your latest.log?

**Comment by Tsuraj56** [comment]
i don't really thing log report will help you to find the issue tho has game is not crashing you will not find any useful in log report if the game crash you will the cause of the crash but you can't see why the mod is not working properly in log reports

**Comment by RodoFire** [comment]
the log can give some informations. It doesn't have to crash to be useful (some `OutOfBound` Exeptions will jut print in the logs what's been wrong without the game crashing)

**Comment by RodoFire** [comment]
the problem is fixed. 
- Why does it crashes/ don't work? Carpet modify the entire logic behind pistons while I only change the ability to push more or less blocks. The mixin wasn't compatible with the piston's logic with carpet.
- What did I done to solve this issue? The mixin will now not be applied when coupled with carpet. This means that the mod is desactivated and doesn't do anything when used with the carpet mod.
